{% set name = "zest.releaser" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zest.releaser-{{ version }}.tar.gz
  sha256: 9b6495d02e594b318862f35cec84c596bf3fe37842db0009c39201f2ebcef809

build:
  entry_points:
    - release = zest.releaser.release:main
    - prerelease = zest.releaser.prerelease:main
    - postrelease = zest.releaser.postrelease:main
    - fullrelease = zest.releaser.fullrelease:main
    - longtest = zest.releaser.longtest:main
    - lasttagdiff = zest.releaser.lasttagdiff:main
    - lasttaglog = zest.releaser.lasttaglog:main
    - addchangelogentry = zest.releaser.addchangelogentry:main
    - bumpversion = zest.releaser.bumpversion:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - colorama
    - python >=3.7
    - requests
    - setuptools
    - tomli
    - twine >=1.6.0

test:
  imports:
    - zest
  commands:
    - pip check
    - release --help
    - prerelease --help
    - postrelease --help
    - fullrelease --help
    - longtest --help
    - git init
    - lasttagdiff --help
    - lasttaglog --help
    - addchangelogentry --help
    - bumpversion --help
  requires:
    - pip
    - git

about:
  home: https://github.com/zestsoftware/zest.releaser
  doc_url: https://zestreleaser.readthedocs.io
  summary: Software releasing made easy and repeatable
  license: GPL-2.0-only
  license_file:
    - LICENSE.GPL

extra:
  recipe-maintainers:
    - thewchan
