{% set name = "zest.releaser" %}
{% set version = "9.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zest.releaser-{{ version }}.tar.gz
  sha256: f6cdbb15a125838144135176182e42d5b04eaae467df9d7b1e77ac24dd4d6266

build:
  entry_points:
    - release = zest.releaser.release:main
    - prerelease = zest.releaser.prerelease:main
    - postrelease = zest.releaser.postrelease:main
    - fullrelease = zest.releaser.fullrelease:main
    - longtest = zest.releaser.longtest:main
    - lasttagdiff = zest.releaser.lasttagdiff:main
    - lasttaglog = zest.releaser.lasttaglog:main
    - addchangelogentry = zest.releaser.addchangelogentry:main
    - bumpversion = zest.releaser.bumpversion:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - python >={{ python_min }}
    - python-build >=1.0.0
    - readme_renderer >=40
    - requests
    - setuptools >=61.0.0
    - tomli
    - twine >=1.6.0

    # From readme_renderer[md]
    - cmarkgfm >=0.8.0

test:
  imports:
    - zest
  commands:
    - pip check
    - release --help
    - prerelease --help
    - postrelease --help
    - fullrelease --help
    - longtest --help
    - git init
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git commit --allow-empty -m "Empty-Commit"
    # - lasttagdiff --help
    # - lasttaglog --help
    - addchangelogentry --help
    - bumpversion --help
  requires:
    - pip
    - git
    - python {{ python_min }}

about:
  home: https://github.com/zestsoftware/zest.releaser
  doc_url: https://zestreleaser.readthedocs.io
  summary: Software releasing made easy and repeatable
  license: GPL-2.0-only
  license_file:
    - LICENSE.GPL

extra:
  recipe-maintainers:
    - thewchan
